<div class="ui grid">
    <div class="row">
        <div class="one column">	
            <h1><?= $this->translate('Accès non autorisé') ?></h1>
            <div class="ui grid">    
                <div class="column">     
                    <div class="ui red large message">
                        <i class="lock big icon"></i>
                        <?= $this->translate("Vous n'êtes pas habilité à accéder à cette page sans authorisation.") ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>