<div class="ui grid">
    <div class="row">
        <div class="one column">	
            <h1><?= $this->translate('Cette page n'éxiste pas (Erreur 404)') ?></h1>
            <div class="ui grid">
                <div class="column">     
                    <div class="ui red large message">
                        <i class="lock big icon"></i>
                        <?= $this->translate("Exception") ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>